apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: webapp
type: Opaque
stringData:
  POSTGRES_DB: mydb
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: webapp
type: Opaque
stringData:
  S3_ACCESS_KEY: test
  S3_SECRET_KEY: test
  S3_REGION: us-west-1
  BUCKET: my-bucket
  EMAIL_USER: ""
  EMAIL_PASSWORD: ""
