version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8082:8081"      # Nexus UI
      - "8083:8083"      # Docker Registry (hosted)
      - "8084:8084"      # Docker Registry (proxy)
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx1024m -XX:MaxDirectMemorySize=1024m
    networks:
      - app_docker_compose_app-net
    restart: unless-stopped

volumes:
  nexus-data:
    driver: local

networks:
  app_docker_compose_app-net:
    external: true
